## General pipeline parameters:

# working directory: all results will be stored within this directory
workdir: ""

# path to ER file or any BED file - should contain columns named seqnames, start, end, strand, id
# see /test_data for demo files
# contig names should be UCSC style - starting with "chr"
ers: ""

# prefix of all output files
sample_name: ""


# PhastCons Bigwig file from UCSC
phastcons: ""

# mm10 repeatmasker data - make sure the seqnames match your er data
# Modify the file using the following commands
# awk -F " " '{print $5" "$6" "$7" "$11}' mm10.fa.out | sed 1,3d > mm10.repeatMasker.mod.fa.out
repeats: ""

# Expression data: directory containing sample bigwigs for calculating expression features
# all files with ".bw" will be read from this directory
# Can be one or multiple (replicates) bigwigs. In case of multiple bigwigs, mean expression will be calculated.
# contig names in the bigwig should be UCSC style - starting with "chr"
bigwig_dir: ""

## chromosome names and lengths are required. File containg lengths for mm10 is provided in /data.
## Please change this file according to the contig names
